version: '3.8'

services:
  nexus:
    image: stanislavcrypto/nexus:latest
    container_name: nexus
    restart: unless-stopped
    volumes:
      - ./nexus-data:/root/.nexus
    environment:
      - ORCHESTRATOR_URL=beta.orchestrator.nexus.xyz
    command: ["./target/release/prover", "beta.orchestrator.nexus.xyz"]
